Adding Bamboo Stack
rancher/community-catalog pull request #354
Opened 2016-12-05 13:13 UTC by matisku

2016-12-05 16:33 UTC, galal-hussein commented
@matisku Thanks for your contribution, i tested catalog template on Rancher v1.2.0, but the Bamboo server failed to initialize, i keep seeing the following error:

```
12/5/2016 6:28:28 PMCaused by: java.net.UnknownHostException: e7342f60fa40: No address associated with hostname
12/5/2016 6:28:28 PM	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
12/5/2016 6:28:28 PM	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
12/5/2016 6:28:28 PM	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
12/5/2016 6:28:28 PM	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
12/5/2016 6:28:28 PM	... 28 more
12/5/2016 6:28:28 PM2016-12-05 16:28:28,590 FATAL [finishsetupBackgroundThread] [UpgradeLauncher] Failed to initialise Bamboo container
12/5/2016 6:28:28 PMjava.lang.RuntimeException: java.net.UnknownHostException: e7342f60fa40: e7342f60fa40: No address associated with hostname
12/5/2016 6:28:28 PM	at com.atlassian.security.auth.trustedapps.UIDGenerator.generateUID(UIDGenerator.java:71)
12/5/2016 6:28:28 PM	at com.atlassian.security.auth.trustedapps.BaseEncryptionProvider.generateUID(BaseEncryptionProvider.java:18)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.container.startup.InitialiseTrustedAppsOnStartup.run(InitialiseTrustedAppsOnStartup.java:41)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.container.BambooContainer.start(BambooContainer.java:244)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.upgrade.UpgradeLauncher.upgradeAndStartBamboo(UpgradeLauncher.java:150)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.ww2.actions.setup.FinishSetupAction.execute(FinishSetupAction.java:44)
12/5/2016 6:28:28 PM	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12/5/2016 6:28:28 PM	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12/5/2016 6:28:28 PM	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12/5/2016 6:28:28 PM	at java.lang.reflect.Method.invoke(Method.java:498)
12/5/2016 6:28:28 PM	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:871)
12/5/2016 6:28:28 PM	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1537)
12/5/2016 6:28:28 PM	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:96)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:88)
12/5/2016 6:28:28 PM	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1613)
12/5/2016 6:28:28 PM	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
12/5/2016 6:28:28 PM	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
12/5/2016 6:28:28 PM	at ognl.SimpleNode.getValue(SimpleNode.java:258)
12/5/2016 6:28:28 PM	at ognl.Ognl.getValue(Ognl.java:494)
12/5/2016 6:28:28 PM	at ognl.Ognl.getValue(Ognl.java:458)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:351)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:403)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:349)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:422)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:284)
12/5/2016 6:28:28 PM	at org.apache.struts2.interceptor.BackgroundProcess$1.run(BackgroundProcess.java:58)
12/5/2016 6:28:28 PM	at java.lang.Thread.run(Thread.java:745)
12/5/2016 6:28:28 PMCaused by: java.net.UnknownHostException: e7342f60fa40: e7342f60fa40: No address associated with hostname
12/5/2016 6:28:28 PM	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
12/5/2016 6:28:28 PM	at com.atlassian.security.auth.trustedapps.UIDGenerator.generateUID(UIDGenerator.java:25)
12/5/2016 6:28:28 PM	... 27 more
12/5/2016 6:28:28 PMCaused by: java.net.UnknownHostException: e7342f60fa40: No address associated with hostname
12/5/2016 6:28:28 PM	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
12/5/2016 6:28:28 PM	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
12/5/2016 6:28:28 PM	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
12/5/2016 6:28:28 PM	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
12/5/2016 6:28:28 PM	... 28 more
12/5/2016 6:28:28 PM2016-12-05 16:28:28,594 ERROR [finishsetupBackgroundThread] [FinishSetupAction] Failed to set up Bamboo
12/5/2016 6:28:28 PMjava.lang.RuntimeException: Failed to upgrade
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.upgrade.UpgradeLauncher.upgradeAndStartBamboo(UpgradeLauncher.java:160)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.ww2.actions.setup.FinishSetupAction.execute(FinishSetupAction.java:44)
12/5/2016 6:28:28 PM	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12/5/2016 6:28:28 PM	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12/5/2016 6:28:28 PM	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12/5/2016 6:28:28 PM	at java.lang.reflect.Method.invoke(Method.java:498)
12/5/2016 6:28:28 PM	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:871)
12/5/2016 6:28:28 PM	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1537)
12/5/2016 6:28:28 PM	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:96)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:88)
12/5/2016 6:28:28 PM	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1613)
12/5/2016 6:28:28 PM	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
12/5/2016 6:28:28 PM	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
12/5/2016 6:28:28 PM	at ognl.SimpleNode.getValue(SimpleNode.java:258)
12/5/2016 6:28:28 PM	at ognl.Ognl.getValue(Ognl.java:494)
12/5/2016 6:28:28 PM	at ognl.Ognl.getValue(Ognl.java:458)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:351)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:403)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:349)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:422)
12/5/2016 6:28:28 PM	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:284)
12/5/2016 6:28:28 PM	at org.apache.struts2.interceptor.BackgroundProcess$1.run(BackgroundProcess.java:58)
12/5/2016 6:28:28 PM	at java.lang.Thread.run(Thread.java:745)
12/5/2016 6:28:28 PMCaused by: java.lang.RuntimeException: java.net.UnknownHostException: e7342f60fa40: e7342f60fa40: No address associated with hostname
12/5/2016 6:28:28 PM	at com.atlassian.security.auth.trustedapps.UIDGenerator.generateUID(UIDGenerator.java:71)
12/5/2016 6:28:28 PM	at com.atlassian.security.auth.trustedapps.BaseEncryptionProvider.generateUID(BaseEncryptionProvider.java:18)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.container.startup.InitialiseTrustedAppsOnStartup.run(InitialiseTrustedAppsOnStartup.java:41)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.container.BambooContainer.start(BambooContainer.java:244)
12/5/2016 6:28:28 PM	at com.atlassian.bamboo.upgrade.UpgradeLauncher.upgradeAndStartBamboo(UpgradeLauncher.java:150)
12/5/2016 6:28:28 PM	... 23 more
12/5/2016 6:28:28 PMCaused by: java.net.UnknownHostException: e7342f60fa40: e7342f60fa40: No address associated with hostname
12/5/2016 6:28:28 PM	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
12/5/2016 6:28:28 PM	at com.atlassian.security.auth.trustedapps.UIDGenerator.generateUID(UIDGenerator.j [...]

2016-12-05 16:34 UTC, galal-hussein commented on templates/bamboo/0/docker-compose.yml
> +    image: busybox
@matisku Can you add `net:none`, also you may want to run this container only once

2016-12-11 16:49 UTC, matisku commented on templates/bamboo/0/docker-compose.yml
> +    image: busybox
Hmm, I didn't have such a problem when testing it on my rancher config. I'll check it and let you know.

2016-12-27 23:47 UTC, rawmind0 commented
Hi @matisku ... Thanks for you PR and to contribute... :)

The package was deployed successfully in my environment. But i have some suggestions to get it better. 

I think it would be better to split it separate pieces, bamboo-server, bamboo-agent and postgres:

* Bamboo-server could connect with different db backends, isn't it?? why only postgres?? You could link bamboo-server with a mysql (already in the catalog) or whatever.
* You don't need to lock and maintain a postgres service inside the package. Postgres package would be profitable for more people by itself.
* Bamboo-client: In order bamboo client could have different extra packages installed, you could have different bamboo clients "pools" for specific tasks or whatever and distinc scales. 

 As an example, you could look at gocd or jenkins packages...

Otherwise, could you please add to the README.md, how to setup bamboo once it's deployed?? Or a link to your https://github.com/matisku/bamboo-docker/blob/master/doc/README.md ;)

Just for curiosity, at bamboo-server docker, why don't you install bamboo software at docker build time instead at docker run time?? I mean, why isn't bamboo installed in Dockerfile instead bamboo-server.sh?? 

Best regards...

2016-12-28 00:00 UTC, rawmind0 requested changes

2016-12-28 00:00 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +        - ${postgress_port}:5432
Do you really need to expose postgres port outside rancher??
Please use rancher lb's instead if it's necessary.

2016-12-28 00:00 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +        - ${agent_port}:54663
Could you please use rancher lb's or traefik instead mapping host ports directly??

2016-12-28 00:00 UTC, rawmind0 commented on templates/bamboo/0/rancher-compose.yml
> +      type: "int"
http_port and agent_port questions don't needed if not mapping host ports directly.

2016-12-28 00:00 UTC, rawmind0 commented on templates/bamboo/0/rancher-compose.yml
> +      type: "int"
postgress_port question don't needed if not mapping host ports directly.

2016-12-29 08:12 UTC, matisku commented
Hi. Thanks for tips. I'll work on this and commit my changes.

2017-03-13 12:37 UTC, matisku commented
@rawmind0 Can this be merged?

2017-03-13 13:24 UTC, rawmind0 requested changes

2017-03-13 13:24 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +    image: matisq/bamboo-server:latest
Please, add the docker version instead of latest. Latest is not reproducible.

2017-03-13 13:24 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +    image: postgres:latest
Please, add the docker version instead of latest. Latest is not reproducible.

2017-03-13 13:24 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +    image: matisq/bamboo-agent:latest
Please, add the docker version instead of latest. Latest is not reproducible.

2017-03-13 13:29 UTC, rawmind0 commented
@matisku , sure it could be merge, but please add the change requests, mine and @galal-hussein ones.

If the use of the already created postgresql catalog package is not possible, please set `net:none` in sidekicks and set the version of the dockers instead `latest`.

2017-04-05 12:36 UTC, matisku commented
@rawmind0 AFAIK `net:none` is valid untill docker version 1.12. After this release `network_mode: none` is used. What in this case? Create different version for newer docker?

2017-07-10 12:30 UTC, rawmind0 requested changes

2017-07-10 12:30 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +    net: none
Sorry, my fault, in compose version 2...
```
--    net: none
++    network_mode: none
```

2017-07-10 12:30 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +    net: none
Sorry, mu fault, in compose version 2...
```
--    net: none
++    network_mode: none
```

2017-07-10 12:30 UTC, rawmind0 commented on templates/bamboo/0/rancher-compose.yml
> +    - variable: bamboo_version
Don't needed bamboo question, already implicit..

2017-07-10 12:30 UTC, rawmind0 commented on templates/bamboo/0/rancher-compose.yml
> +  version: "v0.0.1"
May be, better equals to bamboo version? 

```
--  version: "v0.0.1"
++  version: "5.15.3"
```

2017-07-10 12:30 UTC, rawmind0 commented on templates/bamboo/config.yml
> +version: v0.0.1
May be, better equals to bamboo version? 

```
--  version: "v0.0.1"
++  version: "5.15.3"
```

2017-07-10 12:30 UTC, rawmind0 commented on templates/bamboo/0/rancher-compose.yml
> +    load_balancer_config:
Set new lb images configuration...

```
--    load_balancer_config:
--      haproxy_config: {}
++    lb_config:
++      certs: []
++      port_rules:
++      - protocol: http
++        service: bamboo-server
++        source_port: ${lb_http_port}
++        target_port: 8085
```

2017-07-10 12:30 UTC, rawmind0 commented on templates/bamboo/0/docker-compose.yml
> +    image: rancher/load-balancer-service
Set new lb images configuration...
```
  bamboo-server-lb:
    image: rancher/lb-service-haproxy
    ports:
      - ${lb_http_port}
```

2020-07-31 16:19 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:19 UTC, closed without merging