Adding LB for TeamCity Server
rancher/community-catalog pull request #386
Opened 2016-12-29 12:27 UTC by matisku

2017-03-13 12:37 UTC, matisku commented
@rawmind0 Can this be merged?

2017-07-04 11:11 UTC, rawmind0 requested changes

2017-07-04 11:11 UTC, rawmind0 commented on templates/teamcity/1/docker-compose.yml
> +    image: sjoerdmulder/teamcity:latest
Please, use concrete version instead of latest. Latest is not reproducible.

2017-07-04 11:11 UTC, rawmind0 commented on templates/teamcity/1/docker-compose.yml
> +    image: postgres:latest
Please, use concrete version instead of latest. Latest is not reproducible.

2017-07-04 11:11 UTC, rawmind0 commented on templates/teamcity/1/docker-compose.yml
> +services:
Please, use latest version of rancher lb....
```
  teamcity-server-lb:
    image: rancher/lb-service-haproxy
    ports:
      - ${lb_http_port}
```

2017-07-04 11:11 UTC, rawmind0 commented on templates/teamcity/1/rancher-compose.yml
> +      haproxy_config: {}
Set new lb images configuration...
```
--    load_balancer_config:
--      haproxy_config: {}
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: teamcity-server
        source_port: ${lb_http_port}
        target_port: 8111
```

2017-07-04 11:12 UTC, rawmind0 commented
Hi @matisku... thanks so much for the PR.. Sorry for the delay...

Could you please, take a look at change request?? Thanks...

2020-07-31 16:18 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:18 UTC, closed without merging