Update Wordpress template
rancher/community-catalog pull request #419
Opened 2017-02-05 13:56 UTC by janeczku

Fixes issue running on smaller VMs due to DB using a lot of memory (was ~ 256MB, now  ~ 64MB).

2017-02-07 09:41 UTC, rawmind0 commented
Hi @janeczku  .. thanks for your PR ..

Have you consider to use the galera cluster package instead add the database inseide the package?? You could deploy it and link your service with it, and take profit of the already created packaged. What do you think??

Best regards....

2017-02-07 09:46 UTC, rawmind0 requested changes

2017-02-07 09:46 UTC, rawmind0 commented on templates/wordpress/1/rancher-compose.yml
> +      type: "string"
# Add service combo to select database service. You need to deploy it before.
    - variable: "wordpress_db_service"
      description: |
        Choose the database service to use. 
        It's really recommended a dedicated database service just for wordpress.
      label: "Database stack/service"
      default: "galera/galera-lb"
      required: true
      type: "service"

2017-02-07 09:46 UTC, rawmind0 commented on templates/wordpress/1/docker-compose.yml
> +    - db:mysql
# Set the link to database service
-- - db:mysql
++ - ${wordpress_db_service}:mysql

2017-02-07 09:46 UTC, rawmind0 commented on templates/wordpress/1/docker-compose.yml
> +
# Remove database definition. Re-use the galera cluster catalog package.

2017-02-07 09:46 UTC, rawmind0 commented on templates/wordpress/1/rancher-compose.yml
> +db:
# Remove db scale definition

2020-07-31 16:12 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:12 UTC, closed without merging