TeamCity: Update configs, add ability to select server version.
rancher/community-catalog pull request #475
Opened 2017-04-05 11:56 UTC by matisku

2017-07-03 17:00 UTC, rawmind0 requested changes

2017-07-03 17:00 UTC, rawmind0 commented on templates/teamcity/0/docker-compose.yml
> +  teamcity-server-lb:
Please, use latest version of rancher lb....
```
  teamcity-server-lb:
    image: rancher/lb-service-haproxy
    ports:
      - ${lb_http_port}
```

2017-07-03 17:00 UTC, rawmind0 commented on templates/teamcity/0/docker-compose.yml
> +    image: sjoerdmulder/teamcity:${teamcity_version}
Please, use concrete version instead of latest. Optionally, use teamcity_version as type enum with concrete versions.

2017-07-03 17:00 UTC, rawmind0 commented on templates/teamcity/0/rancher-compose.yml
> +    - variable: teamcity_version
Please, use type enum with concrete versions or one entry per version.

2017-07-03 17:00 UTC, rawmind0 commented on templates/teamcity/0/rancher-compose.yml
> +    load_balancer_config:
Set new lb images configuration...
```
--    load_balancer_config:
--      haproxy_config: {}
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: teamcity-server
        source_port: ${lb_port}
        target_port: 8111
```

2017-07-03 17:01 UTC, rawmind0 commented
Hi @matisku ...Thanks for the PR....

could you please take a look at the change request??

thanks...

2020-07-31 16:18 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:18 UTC, closed without merging