Adding JIRA Server stack
rancher/community-catalog pull request #480
Opened 2017-04-07 11:56 UTC by matisku

2017-07-03 16:50 UTC, rawmind0 requested changes

2017-07-03 16:50 UTC, rawmind0 commented on templates/jira/0/docker-compose.yml
> +    image: matisq/jira-server:latest
Please, use concrete version instead of latest. Latest is not reproducible.

2017-07-03 16:50 UTC, rawmind0 commented on templates/jira/0/docker-compose.yml
> +    image: postgres:latest
Please, use concrete version instead of latest. Latest is not reproducible.

2017-07-03 16:50 UTC, rawmind0 commented on templates/jira/0/rancher-compose.yml
> +      haproxy_config: {}
Set new lb images configuration...
```
--    load_balancer_config:
--      haproxy_config: {}
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: jira-server
        source_port: ${lb_port}
        target_port: 8080
```

2017-07-03 16:50 UTC, rawmind0 commented on templates/jira/0/docker-compose.yml
> +
Please, use latest version of rancher lb....
```
  jira-server-lb:
    image: rancher/lb-service-haproxy
    ports:
      - ${lb_http_port}
```

2017-07-03 16:51 UTC, rawmind0 commented
Hi @matisku ...Thanks for the PR....

could you please take a look at the change request??

thanks...

2020-07-31 16:18 UTC, cjellick commented
v

2020-07-31 16:18 UTC, closed without merging