New Relic Servers (add)
rancher/community-catalog pull request #602
Opened 2017-08-24 03:04 UTC by flaccid

Most of this was pulled from the community, so I'm sure there will be changes to pretty it up, just let me know!

2017-12-14 18:11 UTC, rawmind0 requested changes

2017-12-14 18:11 UTC, rawmind0 commented on templates/newrelicservers/0/docker-compose.yml.tpl
> +    io.rancher.container.pull_image: always
Don't need to pull image always.
```
-    io.rancher.container.pull_image: always
```

2017-12-14 18:12 UTC, rawmind0 requested changes

2017-12-14 18:12 UTC, rawmind0 commented on templates/newrelicservers/0/rancher-compose.yml
> +  - variable: "VERSION"
`VERSION` variable is not used anywhere.

2017-12-14 18:13 UTC, rawmind0 commented
Hi @flaccid , thanks so much for your PR.

Please, take a look at changes requested.

2020-07-31 16:39 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:39 UTC, closed without merging