Adding ONAP catalog (Open Network Automation Platform)
rancher/community-catalog pull request #648
Opened 2017-10-31 03:36 UTC by gbarsky

2017-10-31 18:40 UTC, gbarsky commented
Hello, 
I would appreciate any help to figure out why pull request is failing .

Thanks

2017-12-18 16:44 UTC, rawmind0 requested changes

2017-12-18 16:44 UTC, rawmind0 commented on templates/onap/0/rancher-compose.yml
> +  version: "v1.1"
Version value here has to match with `templates/onap/config.yml` version value.

2017-12-18 16:44 UTC, rawmind0 commented on templates/onap/config.yml
> +version: 1.1
Version value here has to match with `templates/onap/0/rancher-compose.yml` version value.

2017-12-18 16:45 UTC, rawmind0 commented
Hi @gbarsky , thank for the PR and contribute.

Build is failing due to version value is not matching. Take a look to the change requested.

2017-12-19 10:47 UTC, rawmind0 commented
Duplicated PR https://github.com/rancher/community-catalog/pull/674

2020-07-31 16:40 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:40 UTC, closed without merging