drive update for kafka
rancher/community-catalog pull request #676
Opened 2017-11-18 03:51 UTC by willb0t

added menu item for kafka

2017-11-18 03:52 UTC, willb0t commented
try one

2017-12-19 10:28 UTC, rawmind0 requested changes

2017-12-19 10:28 UTC, rawmind0 commented on templates/kafka/4/rancher-compose.yml
>        type: "service"
This type "service" is from zk_link variable, you broke it.

2017-12-19 10:28 UTC, rawmind0 commented on templates/kafka/4/docker-compose.yml
> +    - driver: ${kafka_log_dir}
This line is wrong, why did you change it?
```
-    - driver: ${kafka_log_dir}
+    - ${kafka_log_dir}
```

2017-12-19 10:35 UTC, rawmind0 commented
Hi @willb0t , thanks for the PR and contribute. 

PR has some errors and is not working. PR needs to be tested locally before commit. ;)

Please take a look to the changes requested. 

Also, build is failing. You are trying to rename `templates/zookeeper/4/docker-compose.yml.tpl` to `templates/zookeeper/4/docker-compose.yml`, why?? Could you please remove it from the PR??

2020-07-31 16:40 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:40 UTC, closed without merging