Added external flag for environment scoped volumes
rancher/community-catalog pull request #714
Opened 2018-01-06 23:21 UTC by hprotzek

To use an environment scoped volume the option `external: true` is required in the volumes section. If the option is missing, the volume is always stack scoped. The additional flag `ENVIRONMENT_SCOPED` fix the problem.

2018-01-08 11:32 UTC, rawmind0 requested changes

2018-01-08 11:32 UTC, rawmind0 commented on templates/letsencrypt/4/docker-compose.yml.tpl
> +    {{- end }}
Your 'if' statement is not correct. Due to variable is a boolean it always enter into the if. Have you tested it??

Also, like it's specified at https://docs.docker.com/compose/compose-file/compose-file-v2/#external, `external cannot be used in conjunction with other volume configuration keys (driver, driver_opts).`

```
-    {{- end }}
+    {{- else }}
-    {{- if .Values.ENVIRONMENT_SCOPED}}
+    {{- if eq .Values.ENVIRONMENT_SCOPED "true" }}
    external: true
    {{- end }}
+    {{- end }}
```

2018-01-08 11:33 UTC, rawmind0 commented
Hi @hprotzek, thanks for the PR but it's not working.

Please, take a look to requested changes.

2018-01-12 09:59 UTC, hprotzek commented
Updated the boolean statement. Not sure how to comply with the docker compose requirement, because the Rancher doc say's different: [http://rancher.com/docs/rancher/v1.6/en/rancher-services/storage-service/#environment-scoped-1]
If I only add external, how does Rancher knows about the required driver?

2018-01-12 10:38 UTC, rawmind0 commented
If you set `external: true`, it's supposed that volume was already created and exists at docker daemon. Docker just tries to look for it by name, driver and driver_opts are implicit, https://docs.docker.com/compose/compose-file/compose-file-v2/#external
`If set to true, specifies that this volume has been created outside of Compose. docker-compose up will not attempt to create it, and will raise an error if it doesn’t exist.`

Rancher doc you are referencing should be wrong. Thanks, i'll change it.

2018-01-12 10:51 UTC, rawmind0 commented
https://github.com/rancher/rancher.github.io/pull/969

2018-01-12 10:54 UTC, rawmind0 commented
Please, implement `else` part of the changes requested.

2020-07-31 16:42 UTC, cjellick commented
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

2020-07-31 16:42 UTC, closed without merging